// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56_ZZbEWOKC4uM9JqZ-p8gJVOyIi3NpQ',
    appId: '1:1036246170629:web:eb776fc2ae37727a61706c',
    messagingSenderId: '1036246170629',
    projectId: 'revft-1278d',
    authDomain: 'revft-1278d.firebaseapp.com',
    storageBucket: 'revft-1278d.firebasestorage.app',
    measurementId: 'G-7EX8C02LPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB35Mnh-2Wwv6rU7pB25hjCz8ZsUgHaG0',
    appId: '1:1036246170629:android:de9234348369755b61706c',
    messagingSenderId: '1036246170629',
    projectId: 'revft-1278d',
    storageBucket: 'revft-1278d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBNNbXHpwVEG3xHAro9Dc8FS4lmp_Zxs',
    appId: '1:1036246170629:ios:0af3715c6e1f1ba561706c',
    messagingSenderId: '1036246170629',
    projectId: 'revft-1278d',
    storageBucket: 'revft-1278d.firebasestorage.app',
    iosBundleId: 'com.example.gym2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBNNbXHpwVEG3xHAro9Dc8FS4lmp_Zxs',
    appId: '1:1036246170629:ios:0af3715c6e1f1ba561706c',
    messagingSenderId: '1036246170629',
    projectId: 'revft-1278d',
    storageBucket: 'revft-1278d.firebasestorage.app',
    iosBundleId: 'com.example.gym2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56_ZZbEWOKC4uM9JqZ-p8gJVOyIi3NpQ',
    appId: '1:1036246170629:web:dd455637f1747b8361706c',
    messagingSenderId: '1036246170629',
    projectId: 'revft-1278d',
    authDomain: 'revft-1278d.firebaseapp.com',
    storageBucket: 'revft-1278d.firebasestorage.app',
    measurementId: 'G-9P2BE0HFNF',
  );
}
