import os
import sys
from contextlib import contextmanager

# Suppress TensorFlow logging
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['GLOG_minloglevel'] = '2'

import cv2
import mediapipe as mp
import numpy as np
from geometry_checks import GeometryChecks

# Standard MediaPipe Landmarks
try:
    MP_POSE = mp.solutions.pose
except AttributeError:
    # Fallback for some environments
    import mediapipe.python.solutions.pose as MP_POSE

@contextmanager
def suppress_c_logging():
    """
    Redirects C-level stdout and stderr to NUL to suppress persistent MediaPipe warnings 
    and TFLite INFO logs that defy environment variable suppression on Windows.
    """
    if os.name == 'nt':
        null_device = 'NUL'
    else:
        null_device = '/dev/null'
    
    try:
        # Save original fds
        original_stdout_fd = os.dup(sys.stdout.fileno())
        original_stderr_fd = os.dup(sys.stderr.fileno())
        
        # Open null device
        devnull = os.open(null_device, os.O_WRONLY)
        
        # Redirect both to null
        os.dup2(devnull, sys.stdout.fileno())
        os.dup2(devnull, sys.stderr.fileno())
        
        yield
        
    except Exception:
        yield
    finally:
        if 'original_stdout_fd' in locals():
            os.dup2(original_stdout_fd, sys.stdout.fileno())
            os.close(original_stdout_fd)
        if 'original_stderr_fd' in locals():
            os.dup2(original_stderr_fd, sys.stderr.fileno())
            os.close(original_stderr_fd)
        if 'devnull' in locals():
            os.close(devnull)

def get_landmark_coords(landmarks, joint_name, side):
    """
    Helper to get (x, y) coordinates for a specific joint and side.
    Handles 'vertical' and 'horizontal' virtual points.
    """
    if joint_name.lower() in ['vertical', 'horizontal']:
        return joint_name.lower()

    attr_name = f"{side}_{joint_name.upper()}"
    if hasattr(MP_POSE.PoseLandmark, attr_name):
        lm = landmarks[getattr(MP_POSE.PoseLandmark, attr_name)]
        if lm.visibility < 0.5:
            return None
        return np.array([lm.x, lm.y])
    return None


POSE_MODEL = None
def init_worker():
    """Initializer for the worker process to create the Pose model once."""
    global POSE_MODEL
    # Suppress TFLite initialization logs
    with suppress_c_logging():
        POSE_MODEL = MP_POSE.Pose(
            min_detection_confidence=0.5, 
            min_tracking_confidence=0.5, 
            model_complexity=1,
            static_image_mode=False 
        )

def process_video_for_reference(args):
    """
    Process a single video to extract min/max angles for multiple target angles.
    args: (video_path, exercise_name, angle_configs)
    angle_configs: dict of {angle_name: [joint1, joint2, joint3]}
    """
    video_path, exercise_name, angle_configs = args
    
    if not os.path.exists(video_path):
        return None

    # Use the global model instance
    global POSE_MODEL
    if POSE_MODEL is None:
        # Fallback if somehow not initialized (e.g. running locally without pool init)
        init_worker()
        
    pose = POSE_MODEL
    
    cap = cv2.VideoCapture(video_path)
    
    collected_angles = {name: {'left': [], 'right': []} for name in angle_configs}
    
    # We wrap the entire processing loop to suppress the warnings generated by pose.process
    with suppress_c_logging():
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            
            # Convert to RGB
            image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image.flags.writeable = False
            results = pose.process(image)
            
            if results.pose_landmarks:
                landmarks = results.pose_landmarks.landmark
                
                frame_keypoints = {'LEFT': {}, 'RIGHT': {}}
                
                # Global/Central points
                nose_idx = MP_POSE.PoseLandmark.NOSE
                nose_coords = None
                if landmarks[nose_idx].visibility > 0.5:
                    nose_coords = np.array([landmarks[nose_idx].x, landmarks[nose_idx].y])

                target_joints = ['shoulder', 'elbow', 'wrist', 'hip', 'knee', 'ankle']
                
                for side in ['LEFT', 'RIGHT']:
                    for name in target_joints:
                            coords = get_landmark_coords(landmarks, name, side)
                            if coords is not None:
                                frame_keypoints[side][name] = coords
                    # Add nose to each side for convenience in checks
                    if nose_coords is not None:
                        frame_keypoints[side]['nose'] = nose_coords

                # 1. Angle Calculation
                for angle_name, joints in angle_configs.items():
                    for side in ['LEFT', 'RIGHT']:
                        # First pass: validate side
                        valid_side = True
                        real_coords = {}
                        for j in joints:
                            if j not in ['vertical', 'horizontal']:
                                if j in frame_keypoints[side]:
                                    real_coords[j] = frame_keypoints[side][j]
                                else:
                                    valid_side = False
                                    break
                        
                        if not valid_side:
                            continue
                            
                        # Second pass: construct points list including virtuals
                        final_points = []
                        middle_joint_name = joints[1] # The vertex of the angle
                        
                        middle_coords = real_coords[middle_joint_name]
                        
                        for j in joints:
                            if j == 'vertical':
                                # Create a point directly above/below the middle joint
                                final_points.append(np.array([middle_coords[0], middle_coords[1] - 0.5])) 
                            elif j == 'horizontal':
                                # Create point to the side
                                final_points.append(np.array([middle_coords[0] + 0.5, middle_coords[1]]))
                            else:
                                final_points.append(real_coords[j])
                        
                        if len(final_points) == 3:
                            angle = GeometryChecks.calculate_angle(final_points[0], final_points[1], final_points[2])
                            collected_angles[angle_name][side.lower()].append(angle)

                # 2. Geometric Feedback Checks
                # Collect feedback from every frame to build a comprehensive report
                # We use a simple method: check every frame, collect unique messages.
                # In a real app, you might want to debounce or count occurrences.
                for side in ['LEFT', 'RIGHT']:
                    side_keypoints = frame_keypoints[side]
                    # Convert to lower case keys for compatibility with GeometryChecks
                    check_keypoints = {k.lower(): v for k, v in side_keypoints.items()}
                    
                    frame_feedback = GeometryChecks.check_exercise(exercise_name, check_keypoints, side=side.lower())
                    
                    if 'feedback_set' not in locals():
                        feedback_set = set() # Use set for uniqueness
                    
                    for item in frame_feedback:
                        feedback_set.add(item)

    cap.release()
    
    # Process results
    result = {
        'video': os.path.basename(video_path),
        'exercise': exercise_name,
    }
    
    has_data = False
    for angle_name, sides in collected_angles.items():
        for side, values in sides.items():
            if values:
                has_data = True
                result[f"{angle_name}_{side}_min"] = float(np.min(values))
                result[f"{angle_name}_{side}_max"] = float(np.max(values))
            else:
                result[f"{angle_name}_{side}_min"] = None
                result[f"{angle_name}_{side}_max"] = None

    if has_data:
        # Sort feedback for consistent output
        if 'feedback_set' in locals() and feedback_set:
            result['feedback'] = sorted(list(feedback_set))
        else:
            result['feedback'] = []
            
        return result
    return None
